version: '3.8'

services:
  converter-api:
    build:
      context: ./converter-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Mount template directory (update with your actual path)
      - ./scene_templates:/templates:ro
      # Mount project files for testing
      - ./:/project:ro
      # Mount outputs directory for persistence
      - ./outputs:/app/outputs
      # Mount uploads directory for persistence
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
