name: Deploy to Server

on:
  push:
    branches:
      - master   # master branch'e push olunca deploy çalışacak

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repo’yu checkout et
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Deploy via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /home/idearoot/idea.converter.api
            # execute iznini garantiye al
            chmod +x deploy.sh
            # izin problemi olmadan çalıştır
            bash deploy.sh
          debug: true
